### ISSUE TITLE
How can I also download live video

### ISSUE THREAD

**Issue by adwin5** [przemyslawpluta/node-youtube-dl#106]
Thx for the youtube video download module.
But as I tried, I can't download youtube live video.
like the sky news live (https://www.youtube.com/watch?v=y60wDzZt8yg)
Is any suggestion to do that?
Thx

**Comment by przemyslawpluta** [comment]
@adwin5 what option have you tried?

**Comment by adwin5** [comment]
@przemyslawpluta  Oops. I only tried "--format=18" 
I should try other options.
Thx

**Comment by przemyslawpluta** [comment]
As per above looks like avconv was probably built without https support, you have to compile `ffmpeg` with https support.
