### ISSUE TITLE
Trying to extract audio

### ISSUE THREAD

**Issue by knob1** [przemyslawpluta/node-youtube-dl#110]
Hi,

I try to extract the audio of a youtube-dl with the arguments needed, but I only get the video file.

My Code:

```
var video = youtubedl(videoid,
  // Optional arguments passed to youtube-dl.
  ['--extract-audio', '--audio-format=mp3'],
  // Additional options can be given for calling `child_process.execFile()`.
  { cwd: __dirname});

// Will be called when the download starts.
video.on('info', function(info) {
  console.log('Download started');
  console.log('filename: ' + info._filename);
  console.log('size: ' + info.size);
});

video.pipe(fs.createWriteStream('myvideo.mp4'));
```

What is wrong? 
Is there another way (except call the binary directly) ?

**Comment by douineauromain** [comment]
Hello, I have the exact same problem !

`youtube-dl --extract-audio --audio-format mp3 https://youtu.be/cl3b7dDBLpo` is OK, only audio

But :

```
var options = ['--extract-audio', 
                       '--audio-format', 'mp3',
                       '--audio-quality', '7'];
var video = youtubedl(urlForYoutubeDl, options);
video.pipe(fs.createWriteStream('../public/'+songPathName));
```

Got the video in the mp3 :
![video mp3](http://g.recordit.co/H9Lu3F9E9Y.gif)

**Comment by douineauromain** [comment]
Ive seen youtube-dl used by the module is not the last version (2016.05.01) so I tried to do :
`/node_modules/youtube-dl/bin# youtube-dl --extract-audio  --audio-format mp3 https://youtu.be/cl3b7dDBLpo` and it worked correctly so it's not from here

**Comment by Codingale** [comment]
This, I also have this issue.
```
 // Optional arguments passed to youtube-dl.
  ['-x', '--audio-format', 'mp3'],
```
doesn't work nor does `--audio-format=mp3` calling it directly works though it throws errors and leaves me unable to pipe it properly it seems, it does save the file however.

**Comment by douineauromain** [comment]
I will try with this https://github.com/fent/node-ytdl-core by the same author

**Comment by Codingale** [comment]
That works better than this! Now I myself need a JS only thing that can convert any of those formats to MP3 and pipe it to the responce.

**Comment by przemyslawpluta** [comment]
Does the trick https://github.com/przemyslawpluta/node-youtube-dl/blob/master/example/audio.js

**Comment by artz** [comment]
Hey @przemyslawpluta, know you closed this but I've been unable to get an audio file to extract in the same way as executing the binary alone, even trying the exact arguments in your example. 

See my example code below to reproduce.  The module code yields a `7690793` byte file in the wrong format.  Executing the binary directly yields a `152017` file correctly.  

Let me know your thoughts, thanks!

```javascript
const downloader = require('youtube-dl')

async function testYoutubeDl() {
    const url = 'https://www.youtube.com/watch?v=4ZdfVK0RFxY'
    const download = downloader(
        url,
        [ '--format',  'bestaudio', '--extract-audio', '--audio-format', 'opus', '--audio-quality', '0' ],
        { maxBuffer: Infinity }
    )
    download.on('info', (info) => {
        console.log('info', info._filename, info.size)
    }).on('error', (error) => {
        console.error('error', error)
    });
}

const { exec } = require('child_process');
async function testYoutubeDlExec() {
    const url = 'https://www.youtube.com/watch?v=4ZdfVK0RFxY'
    exec('../node_modules/youtube-dl/bin/youtube-dl --format "bestaudio" --extract-audio --audio-format "opus" --audio-quality 0 --output "correct.%(ext)s" ' + url, (err, stdout, stderr) => {
        console.log('stdout', stdout)
    })
}

testYoutubeDl()
testYoutubeDlExec()
```
