### ISSUE TITLE
Both audio and video being downloaded

### ISSUE THREAD

**Issue by LeoNero** [przemyslawpluta/node-youtube-dl#117]
Hi. I'm trying to get only the audio of a video, but I always get both (one file is a video and other is an audio).

```
var url = 'https://www.youtube.com/watch?v=' + videoId;

youtubedl.exec(url, ['-x', '--audio-format', 'mp3'], {}, function exec(err, output) {
       if (err) { throw err; }
       console.log(output.join('\n'));
});
```

How can I extract only the audio?

**Comment by tonkku107** [comment]
`-x` doesn't do anything, because it's a post-processor argument. I use `-f bestaudio` with youtube.

**Comment by brismuth** [comment]
Are the formats documented somewhere? This issue can probably be closed if they are.

**Comment by przemyslawpluta** [comment]
Have a look at https://github.com/przemyslawpluta/node-youtube-dl/blob/master/example/audio.js

**Comment by mayeaux** [comment]
Thanks @tonkku107 I didn't realize the post-processing commands were documented differently
