### ISSUE TITLE
Progress Bar ?

### ISSUE THREAD

**Issue by LeoCreer** [przemyslawpluta/node-youtube-dl#119]
Is there an on('event', fun(event){
progress ?
});

Can we get the progress of the download from write stream pipe?

**Comment by LeoCreer** [comment]
video.on('readable',function(){

            console.log(video.read());
        });

**Comment by LeoCreer** [comment]
Im going to do a pull request to add progress bar !!! if its ok with you !

**Comment by epilande** [comment]
@LeoCreer something like this should work

```javascript
let size = 0;
video.on('info', (info) => {
  size = info.size;
});

let pos = 0;
let progress = 0;
video.on('data', (chunk) => {
  pos += chunk.length;
  if (size) {
    progress = (pos / size * 100).toFixed(2);
  }
});
```

**Comment by puranjayjain** [comment]
you could also take a look at this module - 
https://www.npmjs.com/package/progress-stream

**Comment by yafp** [comment]
> you could also take a look at this module -
> https://www.npmjs.com/package/progress-stream

Have you ever used this with youtube.exec?

**Comment by puranjayjain** [comment]
Nope @yafp
