### ISSUE TITLE
can I rename the coverted mp3 file

### ISSUE THREAD

**Issue by cloudman1978** [przemyslawpluta/node-youtube-dl#123]
hello,
Is it possible, to specify the name of the output mp3 when downloading and converting a youtube video?
Regards

**Comment by matheuschimelli** [comment]
`var localVideo = path.join(__dirname + '/downloads',trackName'.mp4')
video.pipe(fs.createWriteStream(localVideo));`
insert this code inide video.on callback function.
Change trackName to you variable or video name.
