### ISSUE TITLE
How to call youtube-dl binary directly?

### ISSUE THREAD

**Issue by ghost** [przemyslawpluta/node-youtube-dl#124]
The documentation states that you can "use ytdl.exec() to call youtube-dl however you like." 

Is there an example of how that could be done? I couldn't find anything in the documentation that explains this.

Thanks in advance!

**Comment by MkkCstr** [comment]
https://github.com/fent/node-youtube-dl#call-the-youtube-dl-binary-directly

**Comment by schmod** [comment]
It's worth noting that the node module strips [_a lot_ of parameters](https://github.com/przemyslawpluta/node-youtube-dl/blob/master/lib/util.js#L3) off of the command-line, which may make it difficult/impossible for this to do what you want it to.

**Comment by Rob-pw** [comment]
@schmod, thanks for pointing that out - not present in documentation.
