### ISSUE TITLE
Abort a download

### ISSUE THREAD

**Issue by etienne-gauvin** [przemyslawpluta/node-youtube-dl#125]
Hello,
I'm looking for the possibility to abort an unfinished download.
Is there any way to do that ?

I didn't find anything in the Node documentation (https://nodejs.org/api/stream.html) about it.
Thank you by advance.

**Comment by dimd13** [comment]
+1

**Comment by RenzHoly** [comment]
+1

**Comment by dimd13** [comment]
I found and use this solution
`video._source.stream.abort();`
where `video` is a handler

**Comment by puranjayjain** [comment]
you could also do this
```
video.pause();
video.unpipe()
```

**Comment by Tzahi12345** [comment]
This isn't possible when calling the youtube binary directly, at least not now. But, it should be possible: the execa module used does return a child process. This can be used to manually kill the download as needed.

For now, I'm getting around this limitation by using [ps-node](https://github.com/neekey/ps) to find and kill the relevant process. 

```
function killAllDownloads() {
    var ps = require('ps-node');
    ps.lookup({
        command: 'youtube-dl',
        }, function(err, resultList ) {
        if (err) {
            // failed to get list of processes
        }
        
        // processes that contain the string 'youtube-dl' in the name will be looped
        resultList.forEach(function( process ){
            if (process) {
                // filter out the relevant process in here -- in this case no filtering is done so all will be killed
                console.log( 'PID: %s, COMMAND: %s, ARGUMENTS: %s', process.pid, process.command, process.arguments );
                // A simple pid lookup
                console.log(process.pid)
                ps.kill(process.pid, 'SIGKILL', function( err ) {
                    if (err) {
                        // failed to kill, process may have ended on its own
                    }
                    else {
                        console.log( 'Process %s has been killed!', process.pid );
                    }
                });
            }
        });
        
    });
}
```

But this isn't perfect and process names can differ by platform and environment. It also takes some time to get the processes and kill each one. Having youtubedl.exec return a child process would be a huge improvement on this!
