### ISSUE TITLE
stdout maxBuffer exceeded

### ISSUE THREAD

**Issue by macdja38** [przemyslawpluta/node-youtube-dl#126]
```
{ Error: stdout maxBuffer exceeded
pvpcraft-1     at Socket.<anonymous> (child_process.js:259:14)
pvpcraft-1     at emitOne (events.js:96:13)
pvpcraft-1     at Socket.emit (events.js:188:7)
pvpcraft-1     at readableAddChunk (_stream_readable.js:177:18)
pvpcraft-1     at Socket.Readable.push (_stream_readable.js:135:10)
pvpcraft-1     at Pipe.onread (net.js:542:20)
pvpcraft-1   cmd: '/docker/pvpcraft/pvpcraft/node_modules/youtube-dl/bin/youtube-dl --dump-json -f best http://www.youtube.com/watch?v=VrD5JrW67t8' }
```

issue cased by calling 

```
youtube-dl.getInfo("http://www.youtube.com/watch?v=VrD5JrW67t8", [], (error)=>{
  console.log(error);
}
```

where youtube-dl is the object provided by requiring this library

**Comment by macdja38** [comment]
After looking through the source I found the options object was passed through allowing the user to specify a maxBuffer size with 
```
youtube-dl.getInfo("url", [], {maxBuffer: 1000*1024}, ()=>{})
```
I'm going to leave this open as I didn't see it in the readme or info example.

**Comment by EstebanFuentealba** [comment]
yes, 
`youtubedl("url" , ['--format=18'], { cwd: __dirname, maxBuffer: 1000*1024 });`

**Comment by macdja38** [comment]
@EstebanFuentealba i didn't see that in theben relevant example or readme, where was it?

**Comment by EstebanFuentealba** [comment]
not mentioned, i read the code

**Comment by wwooww** [comment]
I recommend maxBuffer: Infinity

**Comment by Mochlate** [comment]
What is the drawback to specifying maxBuffer infinity?

**Comment by wwooww** [comment]
@Mochlate Umm.. I has not faced yet...

**Comment by macdja38** [comment]
Fixed in https://github.com/przemyslawpluta/node-youtube-dl/commit/3bb3e4da7df2d674cc751569eb857af8a39f8c11
