### ISSUE TITLE
Error: stdout maxBuffer exceeded

### ISSUE THREAD

**Issue by StefanWerW** [przemyslawpluta/node-youtube-dl#128]
I'm getting this error!

> { [Error: stdout maxBuffer exceeded] 
>  cmd: '/app/node_modules/youtube-dl/bin/youtube-dl --dump-json -f best http://www.youtube.com/watch?v=0h-qh9flX2A' }

**Comment by wwooww** [comment]
var video = youtubedl('http://www.youtube.com/watch?v=0h-qh9flX2A',
                    ['-f=best'],
                    {cwd: __dirname, maxBuffer: Infinity}
                    )

**Comment by wwooww** [comment]
`var video = youtubedl('http://www.youtube.com/watch?v=0h-qh9flX2A',
['-f=best'],
{cwd: __dirname, maxBuffer: Infinity}
)`

**Comment by StefanWerW** [comment]
@wwooww Thanks. Maybe it should be documented.

**Comment by wwooww** [comment]
Right! There is no mention about this...

**Comment by laggingreflex** [comment]
Does this mean that downloads are going into memory buffer before being ***directly*** written to disk?

I have an app that I wish to allow multiple downloads and I hit this error often when multiple files are already being downloaded.

**Comment by wwooww** [comment]
@laggingreflex I'm glad that this has helped you :)

**Comment by nikkanetiya** [comment]
I am also gettting the same error 
`Error: stdout maxBuffer exceeded` on getting video info.
`youtubedl.getInfo('https://www.youtube.com/watch?v=d2oOrbtkIR0', null, function(err, json) {...}`

how to pass maxBuffer with getInfo method?

**Comment by wwooww** [comment]
@nikkanetiya Input `maxBuffer:Infinity` into options :)
`ytdl.getInfo = function getInfo(url, args, options, callback)`

**Comment by nikkanetiya** [comment]
@wwooww Thanks it's working fine now. Silly of me, I was just trying to pass it in second args.

**Comment by wwooww** [comment]
@nikkanetiya Anyone can do that :)
