### ISSUE TITLE
Unable to locate youtube-dl details 

### ISSUE THREAD

**Issue by Dovahkiin-Warrior** [przemyslawpluta/node-youtube-dl#131]
As simple as the title says, 
![image](https://cloud.githubusercontent.com/assets/16886014/20550964/295de03c-b109-11e6-9aac-8aa24bc76afe.png)

Node.JS 6.9.1
When messing around with files it then says "Unable to locate youtube-dl details in"

**Comment by captainanderz** [comment]
Do `npm rebuild youtube-dl`
That worked for me
