### ISSUE TITLE
Unescaped command line args

### ISSUE THREAD

**Issue by acarl005** [przemyslawpluta/node-youtube-dl#137]
Some youtube video IDs begin with a hyphen. These are not properly quoted, causing `youtube-dl` to interpret it as a command line option.

```js
const ytdl = require('youtube-dl')
ytdl.getInfo('-3VOMOuH05U', (err, info) => console.error(err))
```

```
Error: Command failed: /Users/andy/Documents/stem/alpha/node_modules/youtube-dl/bin/youtube-dl --dump-json -f best -3VOMOuH05U
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: no such option: -3

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
```

**Comment by przemyslawpluta** [comment]
Please provide relevant url.

**Comment by acarl005** [comment]
URL to what exactly? The video I'm trying to get info for? It would be `https://www.youtube.com/watch?v=-3VOMOuH05U`.

The youtube-dl CLI can take a URL or a youtube video ID, so in the code above I've simply provided the video ID rather than the full URL. It does work when the full URL is used, as the URL does not begin with a hyphen. But it breaks when the video ID is used instead because of the hyphen. It's broken for some IDs. It could be fixed by explicitly ending the command line options with `--`. Like so:

```sh
# whats currently generated
$ /path/to/bin/youtube-dl --dump-json -f best -3VOMOuH05U

# what would work for all cases
$ /path/to/bin/youtube-dl --dump-json -f best -- -3VOMOuH05U
```

**Comment by przemyslawpluta** [comment]
@acarl005 you obviously know that you want to download video from YT so to avoid confusion and possible mismatching of services it would be a lot easier if just to pass the youtube url `https://www.youtube.com/watch?v=` before the `id` as per https://github.com/rg3/youtube-dl#how-do-i-download-a-video-starting-with-a-- instead of building that into the module and have possible false positive outcome.
