### ISSUE TITLE
--write-thumbnail parameter doesn't work

### ISSUE THREAD

**Issue by yannbertrand** [przemyslawpluta/node-youtube-dl#138]
https://github.com/rg3/youtube-dl/blob/master/README.md#thumbnail-images

With this option, the thumbnail isn't downloaded

**Comment by przemyslawpluta** [comment]
This does not seems to work properly with current binary either e.g. `../bin/youtube-dl --write-thumbnail https://www.youtube.com/watch?v=t2oVUxTV4WA` would download image and video at the same time.

**Comment by przemyslawpluta** [comment]
@yannbertrand have a look at `1.12.2` master and https://github.com/przemyslawpluta/node-youtube-dl/blob/master/example/thumbs.js
