### ISSUE TITLE
If a video is no longer available the entire query array is stopped short

### ISSUE THREAD

**Issue by Mochlate** [przemyslawpluta/node-youtube-dl#139]
The first video in this list "is not available", but the second is.  When I run this with the direct command:

/node_modules/youtube-dl/bin/youtube-dl --dump-json -f best --ignore-errors http://www.youtube.com/watch?v=SvPZo52X5vo http://www.youtube.com/watch?v=2xJWQPdG7jE

It yields an error on the first guy, but then still lists the info for the second.  

When I run it with the package like so, I just get an error. 

```
var youtubedl = require('youtube-dl');
var queryArr = [
	'http://www.youtube.com/watch?v=SvPZo52X5vo',
	'http://www.youtube.com/watch?v=2xJWQPdG7jE'
	];

youtubedl.getInfo(queryArr, ['--ignore-errors'], {maxBuffer: 10000*1024}, function(err, info) {
	if (err) {
		console.log("err:", err);
	}
	console.log(info);
	for(s in info) {
		console.log(info[s].webpage_url);
	}
});

```

**Comment by Mochlate** [comment]
I updated my post to pass the --ignore-errors to youtube-dl.  Which it does, but I still get an error from your package.  This needs to be changed

**Comment by brismuth** [comment]
+1

**Comment by kobenein** [comment]
**'ignoreerrors:': True**

still raise DownloadError

**Comment by przemyslawpluta** [comment]
Should work now https://github.com/przemyslawpluta/node-youtube-dl/blob/master/example/missing.js
