### ISSUE TITLE
Download videos in parallel (does not work...)

### ISSUE THREAD

**Issue by prime193** [przemyslawpluta/node-youtube-dl#141]
From some quick testing, it seems that even with forked calls using cluster to the youtube-dl module, videos will not download in parallel.  Can someone with more under the hood experience with this module either confirm or refute that observation?   I see multiple node PID's in Activity Monitor in Mac OS X.  Code to be provided if someone takes up this issue.  Much appreciated.

**Comment by przemyslawpluta** [comment]
Drop the example.
