### ISSUE TITLE
Killing early

### ISSUE THREAD

**Issue by Cretezy** [przemyslawpluta/node-youtube-dl#143]
Is it possible to kill the process early? As in stop streaming. I've tried:

```
const video = youtubedl(path);

video.close(); // doesn't work
video.destroy(); // doesn't work
```

**Comment by godleydemon** [comment]
I've been having this problem myself lately. if I send the end event to it, (in your example code there it'd be video.end() ) it does stop playing like it should, even passes the rest of my variables. But for some reason the file stays open and your unable to remove it or edit it or overwrite it.

**Comment by googleboy360** [comment]
I agreees

**Comment by googleboy360** [comment]
Though when i do video.end() it does fire the on done event so it does stop Streaming to a extent

**Comment by przemyslawpluta** [comment]
@Cretezy please provide code example to explain the issue.

**Comment by Cretezy** [comment]
I no longer need this. I decided that downloading the whole file then streaming back from the file system was more reliable, and cached the videos indirectly.
