### ISSUE TITLE
Duration formatting.

### ISSUE THREAD

**Issue by zaza7** [przemyslawpluta/node-youtube-dl#147]
While using this lib to get information about a video/music file the duration formatting makes the output kind of cumbersome to process as it may displays `3:6` or similar. If possible I'd like an option that disables the formatting so that the returned info is seconds as I need the duration in seconds for tracking and so that I can then run it through my own parser to output as `hh:mm:ss` if it's longer than one hour or `mm:ss` if it's under an hour.

**Comment by googleboy360** [comment]
I agree

**Comment by przemyslawpluta** [comment]
This is the default value returned from YT ... `hh:mm:ss` is timecode specific and would have to added in as additional feature.

**Comment by KenanY** [comment]
@przemyslawpluta Really? From what I'm seeing, YT returns the duration in seconds, and this gets formatted by this module:

https://github.com/przemyslawpluta/node-youtube-dl/blob/da47d4d407e53335f22c08c44576f257503c3375/lib/youtube-dl.js#L248

https://github.com/przemyslawpluta/node-youtube-dl/blob/8bc483902ef93c3aa471abb12f113a1ea2ca3ec2/lib/util.js#L50

**Comment by przemyslawpluta** [comment]
Try latest 1.12.2 from master look for `duration_hms`

**Comment by KenanY** [comment]
Adding another instance of a formatted duration is okay, I guess, since at least the new one is more uniform and could be parsed by the user more easily than `duration`. However, in the end, this issue's request is for the raw duration so that the user can format however they like without the need to parse `duration` or `duration_hms` 🤷‍♂️

**Comment by przemyslawpluta** [comment]
@KenanY don't want to replace current `duration` with original as it'll break already existing flow ... in essence you want just `seconds` ... could just add `_duration` that would provide `s`.

**Comment by KenanY** [comment]
Yeah I agree that we don't wanna replace `duration` without a major semver bump. Could just tack on the raw duration from YT as `duration_raw` for example.

**Comment by przemyslawpluta** [comment]
@KenanY try latest master both `_duration_hms` and `_duration_raw`.
