### ISSUE TITLE
process.stdout.cursorTo is not a function 

### ISSUE THREAD

**Issue by moeinrahimi** [przemyslawpluta/node-youtube-dl#148]
I'm trying to download playlist via the playlist.js function example in the docs repo, but i get this error,
also i should note first video of playlist will download
`
1|dler | TypeError: process.stdout.cursorTo is not a function 1|dler | at Readable.data (/home/moein/projects/youtube-dl/controllers/index.js:39:22) 1|dler | at emitOne (events.js:101:20) 1|dler | at Readable.emit (events.js:188:7) 1|dler | at readableAddChunk (_stream_readable.js:176:18) 1|dler | at Readable.push (_stream_readable.js:134:10) 1|dler | at Readable.onreadable (/home/moein/projects/youtube-dl/node_modules/streamify/lib/index.js:82:14) 1|dler | at Readable.g (events.js:291:16) 1|dler | at emitNone (events.js:86:13) 1|dler | at Readable.emit (events.js:185:7) 1|dler | at emitReadable_ (_stream_readable.js:432:10) 1|dler | at emitReadable (_stream_readable.js:426:7) 1|dler | at readableAddChunk (_stream_readable.js:187:13) 1|dler | at Readable.push (_stream_readable.js:134:10) 1|dler | at Request.<anonymous> (_stream_readable.js:794:20) 1|dler | at emitOne (events.js:96:13) 1|dler | at Request.emit (events.js:188:7) 1|dler | at IncomingMessage.<anonymous> (/home/moein/projects/youtube-dl/node_modules/request/request.js:1088:12) 1|dler | at emitOne (events.js:96:13) 1|dler | at IncomingMessage.emit (events.js:188:7) 1|dler | at readableAddChunk (_stream_readable.js:176:18) 1|dler | at IncomingMessage.Readable.push (_stream_readable.js:134:10) 1|dler | at HTTPParser.parserOnBody (_http_common.js:123:22)
`

**Comment by mayeaux** [comment]
Seems like that's not available on Ubuntu, is that what you're using?

**Comment by moeinrahimi** [comment]
@mayeaux  yes I am using ubuntu 16.04, do you know any solution to get this working on ubuntu ?
