### ISSUE TITLE
Uncaught TypeError: fs.existsSync is not a function

### ISSUE THREAD

**Issue by smhv8550** [przemyslawpluta/node-youtube-dl#150]
![13](https://cloud.githubusercontent.com/assets/29019656/26530085/7c26a2ec-4400-11e7-8167-b1a5599bc255.PNG)

I dont know whats the problem here. 
I tried running the code separately in CMD, "node try.js" and it successfully downloaded videos.
But when i combine it to my Chrome Extension code, it gives this error:
Uncaught TypeError: fs.existsSync is not a function

Ive updated both nodeJS version and browserify version to the latest.
Ive installed youtube-dl "npm install youtube-dl"
Am i missing something? Please help.

**Comment by GlitchedTurtle** [comment]
you can't do fs operations in the browser
