### ISSUE TITLE
Youtube-dl download the youtube video directly to amazon s3 bucket

### ISSUE THREAD

**Issue by usamamashkoor** [przemyslawpluta/node-youtube-dl#170]
Hi i am trying to download YouTube video to amazon s3 bucket directly.Is this is something we can do with YouTube-dl or if their is some other work around then please let me know.

Thanks in advance.

**Comment by h3yn3s** [comment]
Saw this ist still open. Have you found a solution yet? 

I solved it this way using [streaming-S3](https://www.npmjs.com/package/streaming-s3)

Example-Code:
```
new streamingS3(
  youtubedl(
    url,
    ['--format=best[ext=mp4]'],
    { cwd: __dirname }
  ),
  s3Config, // containing your auth data, etc.
  {
    Bucket: bucketName,
    Key: fileName, // set your own filename here
    ContentType: 'video/mp4',
  },
  (err, res, stats) => {
    if (err) console.log(err);
    console.log('success', stats);
  }
);

```

**Comment by aniketgundecha2002** [comment]
If anyone still searching, check the below link 
https://cloudonaut.io/download-youtube-videos-with-aws-lambda-and-store-them-on-s3/
