### ISSUE TITLE
--proxy doesn't work with node-youtube-dl library but works in command line(cmd)

### ISSUE THREAD

**Issue by balgopal14** [przemyslawpluta/node-youtube-dl#176]
this video is not available in india
http://www.youtube.com/watch?v=w3FZ7t2zUHI
so i used --proxy to download this video with proxy 167.114.148.5:3128
i run this command in cmd and its work
youtube-dl -4 --rm-cache-dir --proxy 167.114.148.5:3128 http://www.youtube.com/watch?v=w3FZ7t2zUHI

But while  used this with node-youtube-dl javascript library it give me 
Error : status code 403

this is my code
const stream = youtubedl(url, [ '-f ' + quality, '-4', '-c', '--rm-cache-dir', '--proxy', '167.114.148.5:3128'], {cwd: __dirname, maxBuffer: Infinity});

**Comment by dosenXU** [comment]
yes. 
https://github.com/przemyslawpluta/node-youtube-dl/blob/master/lib/youtube-dl.js#L56
i think because here. getinfo will set the proxy.  but use a request downloader the video not add the proxy .
