### ISSUE TITLE
Some weird loop when getinfo using search

### ISSUE THREAD

**Issue by leonekmi** [przemyslawpluta/node-youtube-dl#178]
https://gist.github.com/leonekmi/21614cf40a2cf5eef2517e9f2c450f59

Got with
`ytdl.getInfo(search, ['--default-search="ytsearch"'], callback);`

When using from CLI, it works normally.

**Comment by Kikobeats** [comment]
It should be working fine now, ping me back in order to reopen the issue 🙂
