### ISSUE TITLE
Error with google drive

### ISSUE THREAD

**Issue by jhdscript** [przemyslawpluta/node-youtube-dl#180]
Hello, I m trying to download a file from google drive but i have an issue. Here is the code

var path = require('path');
var fs = require('fs');
var ytdl = require('..');

var video = ytdl("https://drive.google.com/uc?export=download&id=0B5hBTUDdATCCNmtqM3ItcVAyWGM", ['--output=test.output'], {
    cwd: __dirname
});

var size = 0;
video.on('info', function(info) {
    'use strict';
    size = info.size;
    console.log('Got video info');
    var file = path.join(__dirname, info._filename);
    video.pipe(fs.createWriteStream(file));

});

var pos = 0;
video.on('data', function data(chunk) {
    'use strict';
    pos += chunk.length;

    if (size) {
        var percent = (pos / size * 100).toFixed(2);
        process.stdout.cursorTo(0);
        process.stdout.clearLine(1);
        process.stdout.write(percent + '%');
    }
});

video.on('end', function end() {
    'use strict';
    console.log('\nDone');
});

It appears output options is not sent to youtube-dl exe. Any help is appreciated. Regards

**Comment by Kikobeats** [comment]
I think this is a `youtube-dl` thing more than this specific Node.js connector.

Can you try again with the latest connector/youtube-dl version?
