### ISSUE TITLE
 throw errnoException(err, 'spawn');     ^

### ISSUE THREAD

**Issue by brakdag** [przemyslawpluta/node-youtube-dl#182]
throw errnoException(err, 'spawn');
    ^
error in example runing

**Comment by Akinropo** [comment]
you must be using a window, go to the bin folder in node_modules and replace the youtube-dl.exe there with another one you should download here https://rg3.github.io/youtube-dl/download.html it worked for me

**Comment by Akinropo** [comment]
did your replace the former one with the new one?

**Comment by bolahanna44** [comment]
There was no former file with same name !

**Comment by IsaacEmpower** [comment]
It worked for me! Thank you @Akinropo
