### ISSUE TITLE
Assumes any stderr means there's an error

### ISSUE THREAD

**Issue by DuBistKomisch** [przemyslawpluta/node-youtube-dl#183]
Relevant code is here: https://github.com/przemyslawpluta/node-youtube-dl/blob/3349cbb6e067b6c9e7605acfa4f9d1ccc895fb0c/lib/youtube-dl.js#L189

Just because there's output on stderr, doesn't mean an error occured, for example we are seeing python warnings while downloading from google drive. It should check the exit code of the process instead, which according to the node docs you can get as `err.code`.

**Comment by DuBistKomisch** [comment]
Made a change which works for us: https://github.com/przemyslawpluta/node-youtube-dl/compare/master...viviedu:stderr-isnt-err

Doesn't break any tests but hard to what the convoluted logic nearby is expecting.

**Comment by Kikobeats** [comment]
This has been removed 🙂
