### ISSUE TITLE
Twitch vods not working

### ISSUE THREAD

**Issue by DanielGillies** [przemyslawpluta/node-youtube-dl#184]
I'm trying to use this to download twitch vods. Everytime it runs I'm getting a 0 second long video. Here is my code:
```
var video = youtubedl("https://www.twitch.tv/videos/222126089",
        // Optional arguments passed to youtube-dl.
        [],
        // Additional options can be given for calling `child_process.execFile()`.
        { cwd: __dirname });

    // Will be called when the download starts.
    video.on('info', function(info) {
        console.log('Download started');
        console.log('filename: ' + info._filename);
        console.log('size: ' + info.size);
    });

    video.pipe(fs.createWriteStream('test.mp4'));
```

If I replace the url with the one in the example `http://www.youtube.com/watch?v=90AiXO1pAiA` then it downloads fine. This happens with any twitch vod url I try.

**Comment by Kikobeats** [comment]
I think this is a `youtube-dl` thing more than this specific Node.js connector

**Comment by Kikobeats** [comment]
I'm closing that but feel free to comment again in order to reopened
