### ISSUE TITLE
Get thumbnail information along with playlist information.

### ISSUE THREAD

**Issue by ajitgoel** [przemyslawpluta/node-youtube-dl#187]
I am using the following ode to get the playlist information along with the thumbnail information but it does not return the thumbnail information. What am I missing?
Also how can I return a small thumbnail instead of the maximum size thumbnail that is returned by default? 

```
var url='https://www.youtube.com/playlist?list=PLEFA9E9D96CB7F807';
var options = ['-j', '--flat-playlist', '-e', '--get-thumbnail'];
    youtubedl.getInfo(url, options, function(error, urlInformation) 
    {
    });
```

**Comment by Kikobeats** [comment]
I think this is a `youtube-dl` thing more than this specific Node.js connector
