### ISSUE TITLE
Slow download when bestaudio arg

### ISSUE THREAD

**Issue by Guisch** [przemyslawpluta/node-youtube-dl#188]
Hi,

it seems really strange but my downloads are really slow when I pass the '-f bestaudio' arg.
I tested to directly download from the youtube-dl and it is not slow. On the other hand, download speed seems normal when I pass other args like '-f 18'.

My test for this video: https://www.youtube.com/watch?v=6SFD7fz8fWc 

- -f bestaudio: 
File ~ 9.76mb
Downloaded in **193s** with your module
Downloaded in 3s with youtube-dl

- -f 18
File ~ 18.10mb
Downloaded in 5s with your module
Downloaded in 4s with youtube-dl

I've seen on youtube-dl issues (https://github.com/rg3/youtube-dl/issues/15384) that youtube throttles DASH downloads but in this case, why is it still faster when I launch via command ?

Thanks by advance

**Comment by Guisch** [comment]
Ok found why:
If you call node-youtube-dl like that
```
ytdl('https://www.youtube.com/watch?v=AW8OOp2undg',
    // Optional arguments passed to youtube-dl.
    ['-f', 'bestaudio']);
```
Then, node-youtube-dl will exec youtube-dl with '--dump-json' parameter and download itself (throught node) the requested video thanks to what youtube-dl will return.

Otherwise if you call node-youtube-dl like that
```
ytdl.exec(url, ['-f', 'bestaudio'], {}, function exec(err, output) {
    'use strict';
    if (err) { throw err; }
    console.log(output.join('\n'));
});
```
Then, node-youtube-dl will exec youtube-dl directly.
SO, that's why if you pass arg like '-x --audio-format mp3' when calling node-youtube-dl with the first method, it won't transcode into mp3. That's also why download is slow (refer here: https://github.com/rg3/youtube-dl/issues/15384)

**Comment by rzfzr** [comment]
Are you sure it's because of '--dump-json' ? I looked into the code and even passed it, it makes no difference, '--dump-json'  is passed either way
