### ISSUE TITLE
how to get only information without downloadin files ??

### ISSUE THREAD

**Issue by kunaldodiya** [przemyslawpluta/node-youtube-dl#190]
I need only information of file like filename, extension, size etc without downloading the file, is there any special flags available to pass ??

and only works when npm run dev.. doesn't work after building app using electron-packager.. it is giving just a blank object

**Comment by joek85** [comment]
https://github.com/przemyslawpluta/node-youtube-dl#getting-video-information

**Comment by kunaldodiya** [comment]
Thanks
