### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by Lornis** [przemyslawpluta/node-youtube-dl#191]
When running sudo npm install youtube-dl I get this error: ERR! error installing youtube-dl@1.12.2 Error: youtube-dl@1.1.0 postinstall: node ./scripts/download.js . Any idea what may fix this issue?

**Comment by oronbz** [comment]
I'm also experiencing this with newer versions of `npm`, version 5 and above.
It seems to work on 3.10.10

**Comment by pateboyd** [comment]
i am having the same issue with omxplayer for home bridge. what is the work around?

**Comment by Kikobeats** [comment]
I need more environment information in order to debug this.

Also, be sure to install the latest youtube-dl version from `@microlink/youtube-dl`.

Closing until get news!
