### ISSUE TITLE
Using a custom ffmpeg path

### ISSUE THREAD

**Issue by hauketoenjes** [przemyslawpluta/node-youtube-dl#192]
If i try to execute youtube-dl in my javascript, i get an error that there is no such option "--fmpeg-location"
Error:
"youtube-dl.exe: error: no such option: --ffmpeg-location ffmpeg/bin/ffmpeg.exe"

If i execute a command from cmd all works fine. 
Full JS:
let ytDl = require('youtube-dl');
ytDl.exec('https://www.youtube.com/watch?v=3BXDsVD6O10', ['--ffmpeg-location ffmpeg/bin/ffmpeg.exe','-f (bestvideo[width=1920]/bestvideo)+bestaudio/best'], {}, function(err, output){
        if (err) throw err;
        console.log(output.join('\n'));
    });

**Comment by yafp** [comment]
Hi,

i am using `-ffmpeg-location` in an electron project which is currently using node-youtube-dl 2.1.0
So in general using this option does work.
