### ISSUE TITLE
Don't expect the output to be JSON

### ISSUE THREAD

**Issue by Coriou** [przemyslawpluta/node-youtube-dl#198]
I ran into an issue while looking to just get the URL of a media (Youtube video here, but guess you'd get the same problem in other similar situations too) : node-youtube-dl throws a JSON parsing exception because the output from Youtube-dl isn't JSON.

### Reproduce : 

```
import yt from "youtube-dl"

let video = yt( 'SOME_ID', ['-g'] )
video.on( 'info', i => console.log(i) )
```

The `-g` argument means "--get-url" and will make Youtube-dl return an array of strings, rather than the expected JSON string.

Faulty code seems to be (just started using the library, bare with me if I'm wrong) [here](https://github.com/przemyslawpluta/node-youtube-dl/blob/master/lib/youtube-dl.js#L248)

**Comment by polomoshnov** [comment]
As a dirty workaround try replacing `const info = JSON.parse(data);` on [line 241](https://github.com/przemyslawpluta/node-youtube-dl/blob/30922264222e49c8f23dc512ad2c5abaacff72bc/lib/youtube-dl.js#L241) with the following code:
```
var info;
try {
    info = JSON.parse(data);
} catch (err) {
    info = {data: data};
}
```

**Comment by polomoshnov** [comment]
As a workaround, you can get the URL if you pass no options like this: `let video = yt( 'SOME_ID', [] )`.

**Comment by Kikobeats** [comment]
@polomoshnov do you think this could be easy to address in a PR?

I'm a bit out of the context but I understand just we need ward the value, ensuring it's a JSON-like thing.

**Comment by Coriou** [comment]
@polomoshnov @Kikobeats Can you please take a look at #242 ? It fixes this case (`-g` & `--get-url` flags), without breaking previous tests, however I'm not sure wether there's other arguments that produce non-json youtube-dl outputs

**Comment by Coriou** [comment]
Fixed in #242

**Comment by m7mdcc** [comment]
I'm still having this issue ,  version 2.0.0 via NPM .

**Comment by Coriou** [comment]
@m7mdcc Can you provide code that doesn't work please ?

**Comment by m7mdcc** [comment]
> @m7mdcc Can you provide code that doesn't work please ?

Yes sure , 

`
var video = youtubedl(youtube_link,['-g', '--skip-download']);

video.on('info', function(info) {
    console.log(info["formats"]);

  });

###output 

[ { url:
     'https://r2---sn-puj-wxql.googlevideo.com/videoplayback?expire=1559816189&ei=nZP4XJH1BsHV1gae5KKIDQ&ip=xx.xx.xx.xx&id=o-AEbtKM9wDGTDakDOciF7ra6EXJdlZBGvtDqqHLU1uQfO&itag=249&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-puj-wxql%2Csn-hgn7rn7k&ms=au%2Crdu&mv=m&pl=22&initcwndbps=841250&mime=audio%2Fwebm&gir=yes&clen=6389476&dur=1072.661&lmt=1559670894774559&mt=1559794506&fvip=5&keepalive=yes&c=WEB&txp=5531432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=ALgxI2wwRAIgS1m_c9ynLN4sFKHoxqUNApQTn5mtL1H5rN0f9jKY_w8CIGSDGUum0I3WYgqvGjOs3VUqO3mMg9lSxNqSUfT6WXVX&lsparams=mm%2Cmn%2Cms%2Cmv%2Cpl%2Cinitcwndbps&lsig=AHylml4wRQIgcUKcMCcg-CAW_3_aB0Gp89xMvZRDwI5PnfIQiH4jjPgCIQCD4Fqejk513XSL6IkF04awc2EIEvPz4P-23Su7Z8DKTw%3D%3D&ratebypass=yes',
    protocol: 'https',
    format_note: 'DASH audio',
    http_headers:
     { 'Accept-Encoding': 'gzip, deflate',
       'User-Agent':
        'Mozilla/5.0 (X11; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0',
       'Accept-Charset': 'ISO-8859-1,utf-8;q=0.7,*;q=0.7',
       'Accept-Language': 'en-us,en;q=0.5',
       Accept:
        'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' },
    tbr: 55.016,
    abr: 50,
    filesize: 6389476,
    quality: -1,
    vcodec: 'none',
    acodec: 'opus',
    downloader_options: { http_chunk_size: 10485760 },
    format_id: '249',
    format: '249 - audio only (DASH audio)',
    player_url: '/yts/jsbin/player_ias-vflo4i8HU/en_US/base.js',
    ext: 'webm' },
`
