### ISSUE TITLE
Slow getInfo

### ISSUE THREAD

**Issue by ThangTruong921** [przemyslawpluta/node-youtube-dl#199]
Hi.
There is a problem,When getInfo slow 10 seconds
var youtubedl = require('youtube-dl');
var url = 'http://www.youtube.com/watch?v=WKsjaOqDXgg';
// Optional arguments passed to youtube-dl.
var options = ['--username=user', '--password=hunter2'];
youtubedl.getInfo(url, options, function(err, info) {
  if (err) throw err;
 
  console.log('id:', info.id);
  console.log('title:', info.title);
  console.log('url:', info.url);
  console.log('thumbnail:', info.thumbnail);
  console.log('description:', info.description);
  console.log('filename:', info._filename);
  console.log('format id:', info.format_id);
});

**Comment by Kikobeats** [comment]
it should be working fine now.

**Comment by ThangTruong921** [comment]
Thank you
