### ISSUE TITLE
ytdl.getInfo() returns a lot of unnecessary data.

### ISSUE THREAD

**Issue by suraj021** [przemyslawpluta/node-youtube-dl#202]
Suppose I want the info of the format_id= 22 of the youtube video, ytdl.getInfo() returns the info of the format_id along with the info of all the formats available in the "formats" key of the response which causes a delay in the call of the function.
Also there should be an option to not retrieve information about the DASH formats.

**Comment by tuanbs** [comment]
I have the same question. How to get less info to make it faster? I have to wait around 4-5 seconds.

**Comment by tuanbs** [comment]
@suraj021 Option for skipping DASH:
```
--username=,--password=,--youtube-skip-dash-manifest
```

**Comment by Kikobeats** [comment]
good to know, thanks for that 🙂
