### ISSUE TITLE
downloader.js in npm wrong executable

### ISSUE THREAD

**Issue by razorxan** [przemyslawpluta/node-youtube-dl#205]
These lines in downloader.js

    19:  //download the correct version of the binary based on the platform
    20:  url = exec(url);

seem to be missing in the npm module.

So it will always download the linux version of the executable.

**Comment by Shrekie** [comment]
Hey great find, kinda tedious changing the executable every install

**Comment by Kikobeats** [comment]
This should be fixed, consider comment if you see strange behavior there
