### ISSUE TITLE
Status Code 403

### ISSUE THREAD

**Issue by flokol120** [przemyslawpluta/node-youtube-dl#206]
I am getting the following error when trying to download south park episodes of the offical websites.

```
Uncaught Exception:
Error: status code 403
    at Request.response (node_modules/youtube-dl/lib/youtube-dl.js:72:41)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestResponse (node_modules/request/request.js:1068:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:551:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:23)
    at TLSSocket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
```

This is the code I am using: 

```
var video = ytdl('http://southpark.cc.com/full-episodes/s01e01');

  var size = 0;
  video.on('info', function (info) {
    'use strict';
    size = info.size;

    console.log('Got video info');
    var file = path.join(__dirname, info._filename);
    video.pipe(fs.createWriteStream(file));

  });

  var pos = 0;
  video.on('data', function data(chunk) {
    'use strict';
    pos += chunk.length;

    // `size` should not be 0 here.
    if (size) {
      var percent = (pos / size * 100).toFixed(2);
      process.stdout.cursorTo(0);
      process.stdout.clearLine(1);
      process.stdout.write(percent + '%');
    }
  });

  video.on('end', function end() {
    'use strict';
    console.log('\nDone');
  });
```

Everything is working when I try to download the video through the command line. I tried several arguments such as `'-4'`, `'--ignore-errors'` and using https, whilst none of which worked. I pasted both the windows and python version of youtube-dl in the bin folder of this package.

**Comment by yafp** [comment]
@flokol120 
I had several 403 errors in the past, usually it was solveable by updating your youtube-dl version to the latest one.

youtube-dl itself is heavily updated due to changes from streaming services - so in case you are running a non up-to-date youtube-dl version it might be a reason.

node-youtube-dl offers on option to update the youtube-dl binary to the latest version (its explained in the project readme). See if that helps.

**Comment by yafp** [comment]
@flokol120 
can you still reproduce this issue with the current version?

**Comment by flokol120** [comment]
@yafp 
I've switched to the binary of youtube-dl. So it's not in my code anymore, sorry. I'll close this issue for now.
