### ISSUE TITLE
Parameter must be a string, not undefined

### ISSUE THREAD

**Issue by alee046** [przemyslawpluta/node-youtube-dl#209]
Currently trying to use youtubedl, following the usage example. The url we are passing is quite long with quite a bit of query strings. When passing the whole url as is, we get an error of 
"Parameter must be a string, not undefined"

When we wrap the url in quotes ( '"' + https//:url +  '"'), we get an error of
unsupported protocol, trying with http.

Does anyone know what the possible issue could be?

**Comment by lightbringer1991** [comment]
can you post the full url plus the snippet of your script?

**Comment by yafp** [comment]
@alee046 
any updates you can provide?

**Comment by Kikobeats** [comment]
Happy to open again the issue if more information is attached 🙂

**Comment by yafp** [comment]
;)
