### ISSUE TITLE
Extracting the subtitles as plain text

### ISSUE THREAD

**Issue by magician11** [przemyslawpluta/node-youtube-dl#211]
I'm trying to figure out how to extract the subtitles as plain text, as opposed to the default vtt.

I had a look at the [youtube-dl docs](https://github.com/rg3/youtube-dl/blob/master/README.md#subtitle-options) and it's not clear to me.

Also the [options passed to this module](https://github.com/przemyslawpluta/node-youtube-dl#downloading-subtitles), look a little different to the core module options.. so I'm not sure how to construct my object either.

Or do I need to post-process the vtt to extract the plain text? Any suggestions as to how to do that?

Thanks.

**Comment by hugolpz** [comment]
I try to output srt, from the vtt.
First, I found difficult the lack of API. The need to refer to [/rg3/youtube-dl](https://github.com/rg3/youtube-dl/blob/master/README.md#subtitle-options) isn't clear enough.
Secondly, I noticed [/lib/youtube-dl.js](https://github.com/przemyslawpluta/node-youtube-dl/blob/3349cbb6e067b6c9e7605acfa4f9d1ccc895fb0c/lib/youtube-dl.js#L320-L359), which is actually building the command for rg3/youtube-dl/ . So I tried to edit it, adding the following (unsuccessfully): 
 
``` 
    if (options.format) {
        args.push('--sub-format=' + options.format);
    }
```

I think the main issue is : I don't see how to process the vtt data, where, within [this subtitle example](https://github.com/przemyslawpluta/node-youtube-dl/blob/3349cbb6e067b6c9e7605acfa4f9d1ccc895fb0c/README.md#downloading-subtitles)

```javascript
var options = {
  // Write automatic subtitle file (youtube only)
  auto: false,
  // Downloads all the available subtitles.
  all: false,
  // Languages of subtitles to download, separated by commas.
  lang: 'en',
  // The directory to save the downloaded files in.
  cwd: __dirname,
};
youtubedl.getSubs(url, options, function(err, files) {
  if (err) throw err;

  console.log('subtitle files downloaded:', files);
});
```

**Comment by magician11** [comment]
@hugolpz I've been researching this more since I posted this. My solution to extract subtitles is as follows now...

```
const { getSubtitles } = require('youtube-captions-scraper');
const getYouTubeID = require('get-youtube-id');

const getYouTubeSubtitles = async youtubeUrl => {
  try {
    const videoID = getYouTubeID(youtubeUrl);
    const subtitles = await getSubtitles({ videoID });
    return subtitles.reduce(
      (accumulator, currentSubtitle) =>
        `${accumulator} ${currentSubtitle.text}`,
      ''
    );
  } catch (error) {
    console.log(`Error getting captions: ${error.message}`);
  }
};

(async () => {
  const consoleArguments = process.argv;
  if (consoleArguments.length !== 3) {
    console.log(
      'usage example: node get-youtube-subtitles.js https://www.youtube.com/watch?v=gypAjPp6eps'
    );
    return;
  }

  const subtitles = await getYouTubeSubtitles(consoleArguments[2]);
  console.log(subtitles);
})();
```



I wrote about my findings [here](https://golightlyplus.com/how-to-programatically-extract-youtube-captions-as-plain-text/).

**Comment by Kikobeats** [comment]
Just as an addition, recently was added support for selecting subtitle format https://github.com/przemyslawpluta/node-youtube-dl/pull/235 🙂.

Please, if the solution by @magician11 was helpful, you can add it as README as an example user case for the benefit the rest of users.
