### ISSUE TITLE
Error: spawn UNKNOWN

### ISSUE THREAD

**Issue by epancentcev** [przemyslawpluta/node-youtube-dl#215]
При установки 
npm i imagemin-pngquant
Выводит вот
$ npm i imagemin-pngquant --save-dev

> pngquant-bin@5.0.0 postinstall C:\Users\home\Desktop\web_site\node_modules\p
ngquant-bin
> node lib/install.js

internal/child_process.js:358
    throw errnoException(err, 'spawn');
    ^

Error: spawn UNKNOWN
    at ChildProcess.spawn (internal/child_process.js:358:11)
    at spawn (child_process.js:533:9)
    at C:\Users\home\Desktop\web_site\node_modules\bin-check\index.js:22:12
    at C:\Users\home\Desktop\web_site\node_modules\executable\index.js:27:4
    at FSReqWrap.oncomplete (fs.js:155:5)
npm WARN website@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\f
sevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevent
s@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"i
a32"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pngquant-bin@5.0.0 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pngquant-bin@5.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional l
ogging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\home\AppData\Roaming\npm-cache\_logs\2018-10-02T11_59_35
_794Z-debug.log

Как можно исправить, у кого было такое?

**Comment by jalaka** [comment]
Somehow I solved this problem you have by downloading the binary for youtube-dl from the original site and replace the version inside of node_modules/youtube-dl/bin with that version.

**Comment by Gyzimo** [comment]
Yeah that worked for me. 
Just replacing the old youtube-dl.exe with the new version fixed it !

**Comment by StefanWerW** [comment]
Same problem here

**Comment by aromot** [comment]
Sorry, I feel stupid, but where can I get the binary (from the original site)?

**Comment by Gyzimo** [comment]
i am not sure where i got it.. 
someone posted a link to the DL file. 
but i uploaded the file i use to google drive if you like
https://drive.google.com/open?id=1o6h7ffnTsnGFme-bM8lGJaKCV_c9ia9J

**Comment by Gyzimo** [comment]
Oh no nvm i found that the website
https://rg3.github.io/youtube-dl/download.html

![image](https://user-images.githubusercontent.com/9869893/47520294-1b514000-d890-11e8-9b9d-6b712dbe3aca.png)


That is where you get the file

**Comment by atifmajeed** [comment]
updated packages "protractor-cucumber-framework": "6.2.0" and protractor-multiple-cucumber-html-reporter-plugin": "1.8.1" that fixed this issue
