### ISSUE TITLE
Firebase function Error

### ISSUE THREAD

**Issue by 345ml** [przemyslawpluta/node-youtube-dl#219]
I implemented the API in the Firebase Function, and I am using this wonderful library there.
This API returns Buffer of video.
The client sends a Fetch request and uses the received Biffer to perform the download process.
It will run successfully in the local environment.

However, when deploying to Firebase functins and accessing the API, an error occurs.
```
// Request from Fetch
 No 'Access-Control-Allow-Origin' header is present on the requested resource.
```
```
// Request from Blowser
Error: could not handle the request
```

This seems to occur for videos longer than 1 minute.
Video shorter than that can successfully download videos.

Is there implementation example with Firebase Functions or Cloud Functions?

**Comment by 345ml** [comment]
My implementation is this.

```node.js
const express = require('express');
const router = express.Router();
const youtubedl = require('youtube-dl');
const fs = require('fs');
const cors = require('cors');

router.get('/download', cors({origin: true}), function(req, res, next) {
  const video = youtubedl(req.query.url,
    // Optional arguments passed to youtube-dl.
    ['--format=18'],
    // Additional options can be given for calling `child_process.execFile()`.
    { cwd: __dirname });

  let buffer = [];
  let filename;
  // Will be called when the download starts.
  video.on('info', function(info) {
    filename = info._filename;
  });

  video.on('data', function(data) {
    buffer.push(data);
  });

  video.on('end', function(data) {
    buffer = Buffer.concat(buffer);
    res.json({ buffer, filename });
  });

  video.on('error', function(error) {
    next(error);
  });
});

module.exports = router;
```

**Comment by EddieEJ** [comment]
Any progress on this?

**Comment by Kikobeats** [comment]
I can't provide any insights about that since I'm deploying nothing to Firebase.

However, I have a tiny microservice using `youtube-dl` and this connector under AWS Lambda and it is working fine.

The infrastructure should be not a condition for running the command, so something infrastructure specific is happening there.
