### ISSUE TITLE
How to set the destination location?

### ISSUE THREAD

**Issue by reger-men** [przemyslawpluta/node-youtube-dl#222]
Is there any way to set the destination of the output audio file?
I used this example:

```
var url = 'https://www.youtube.com/watch?v=H7HmzwI67ec';
ytdl.exec(url, ['-x', '--audio-format', 'mp3'], {}, function exec(err, output) {
    'use strict';
    if (err) { throw err; }
    console.log(output.join('\n'));
});
```
I already tested this option `-o test.mp4` but it doesn't work.

Thanks.

**Comment by pthieu** [comment]
I would also like to know this as pipes don't automatically combine audio and video but using `ytdl.exec` does.

**Comment by pthieu** [comment]
Just ran into this issue, you can do something like this:

```
youtubedl.exec(url, [`-o ${downloadDir}/%(title)s.%(ext)s`], {}, () => {...})
```

**Comment by reger-men** [comment]
Thank you @pthieu!

This one work now well for me:
```
youtubedl.exec(url, ['--audio-format', 'mp3', '--output', 'Your/Path/file.mp3'], {}, function exec(err, output) {
              if (err) { throw err; }
                  console.log("...");
});
```

**Comment by pthieu** [comment]
@reger-men ah your last message just gave me a clue about another issue I was having #223
