### ISSUE TITLE
Space in download path when using `.exec` method and `-o` option

### ISSUE THREAD

**Issue by pthieu** [przemyslawpluta/node-youtube-dl#223]
Just using the standard examples on the `README.md`, I want to download to a folder that I don't care to be persistent: `/tmp`. Download works but it created a spaced directory so it downloads to a location like: `__dirname/ /tmp/...`

Reproduction code:

```
const fs = require('fs');
const youtubedl = require('youtube-dl');

const url = 'https://v.redd.it/132f0azg8zy11/DASH_9_6_M';

youtubedl.exec(url, ['-o /tmp/%(title)s.%(ext)s'], {}, function(err, output) {
  if (err) throw err;
  console.log(output.join('\n'));
});
```

And the output is:

```
[Reddit] 132f0azg8zy11: Downloading m3u8 information
[Reddit] 132f0azg8zy11: Downloading MPD manifest
[download] Destination:  /tmp/132f0azg8zy11.fdash-VIDEO-4.mp4
[download] 100% of 6.58MiB in 00:0064MiB/s ETA 00:00known ETA
[download] Destination:  /tmp/132f0azg8zy11.fdash-AUDIO-1.m4a
[download] 100% of 94.63KiB in 00:0071MiB/s ETA 00:00:00wn ETA
[ffmpeg] Merging formats into " /tmp/132f0azg8zy11.mp4"
Deleting original file  /tmp/132f0azg8zy11.fdash-VIDEO-4.mp4 (pass -k to keep)
Deleting original file  /tmp/132f0azg8zy11.fdash-AUDIO-1.m4a (pass -k to keep)
```

This might be an issue with my understanding of `youtube-dl` because I can do `-o/tmp...` and it will not have the space.

**Comment by pthieu** [comment]
Turns out this module does a join on the params array, was given a clue here: https://github.com/przemyslawpluta/node-youtube-dl/issues/222#issuecomment-455184537

**Comment by Tzahi12345** [comment]
I'm having a related issue where on Linux, if there is a space in the download path, it fails.

Ex:

```
youtubedl.exec(url, ['-o', '/tmp/%(id)s %(title)s.%(ext)s'], {}, function(err, output) {
```
