### ISSUE TITLE
Error getting video url

### ISSUE THREAD

**Issue by ddimka** [przemyslawpluta/node-youtube-dl#224]
In last version I get:

Error getting video url: Error: Command failed: /var/www/back/node_modules/youtube-dl/bin/youtube-dl --dump-json --force-ipv4 --format=18 http://www.youtube.com/watch?v=k4YRWT_Aldo

ERROR: Signature extraction failed: Traceback (most recent call last):
File "/var/www/telll/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1225, in _decrypt_signature
video_id, player_url, s

File "/var/www/telll/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1133, in _extract_signature_function
res = self._parse_sig_js(code)

File "/var/www/telll/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1200, in _parse_sig_js
initial_function = jsi.extract_function(funcname)

File "/var/www/telll/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/jsinterp.py", line 245, in extract_function
raise ExtractorError('Could not find JS function %r' % funcname)

ExtractorError: Could not find JS function u'encodeURIComponent'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError(u"Could not find JS function u'encodeURIComponent'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Can someone help?

**Comment by Kikobeats** [comment]
It's a [recurrent issue at youtube-dl](https://github.com/ytdl-org/youtube-dl/search?q=encodeURIComponent+is%3Aissue&type=Issues) sorry if I can't provide more context
