### ISSUE TITLE
Unexpected token '...'

### ISSUE THREAD

**Issue by EddieEJ** [przemyslawpluta/node-youtube-dl#227]
I am trying to use this wonderful library in Firebase functions. Whenever I try to use the `getInfo()` method, I am getting the following error:
![image](https://user-images.githubusercontent.com/25306489/52515405-0d42e780-2c13-11e9-8b22-954dc1b28f59.png)

Here is what my function looks like:
```
exports.getURLInfo = functions.https.onRequest((request, response) => {
    let myObj = {};
    youtubedl.getInfo(request, function(err, info) {
        if (err) throw err;
      
        myObj["id"]= info.id;
        myObj["title"]=  info.title;
        myObj["url"]=  info.url;
        myObj["thumbnail"]=  info.thumbnail;
        myObj["description"]=  info.description;
        myObj["filename"]=  info._filename;
        myObj["formatID"]=  info.format_id;
      });
    response.send(myObj);
});

```
I would appreciate any help provided.

**Comment by hi-too** [comment]
Same here..!!

**Comment by joshgare** [comment]
This isn't an issue with this library it is related to how you configure your Firebase project.

Firebase by default uses Node v6 but this library relies on the spread operator which isn't available in Node v6.

You can fix this by upgrading your Firebase project to Node v8. To do this you can add `"engines": {"node": "8"}` to your package.json.

**Comment by hi-too** [comment]
Indeed.. I upgraded my Node version, and got the issue resolved.

One "BIG" thumb to this amazing library..

**Comment by joshgare** [comment]
@hi-too did you manage to get the library to run on Firebase? I tried deploying this and creating a simple REST API on a Firebase functions.

My function deployed without a problem as I set the Node version to v8. However an error was thrown because of the Python executable.

```
{ Error: Command failed: /srv/node_modules/youtube-dl/bin/youtube-dl --dump-json -f best http://www.youtube.com/watch?v=pmoHdoNAh3E
/usr/bin/env: 'python': No such file or directory

    at ChildProcess.exithandler (child_process.js:281:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Socket.stream.socket.on (internal/child_process.js:336:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:561:12)
  killed: false,
  code: 127,
  signal: null,
  cmd: '/srv/node_modules/youtube-dl/bin/youtube-dl --dump-json -f best http://www.youtube.com/watch?v=pmoHdoNAh3E' }
```

**Comment by kieuquangloc147** [comment]
@joshgare @EddieEJ do you resolve the problem?
