### ISSUE TITLE
--max-filesize doesn't always work - inconsistent

### ISSUE THREAD

**Issue by ndtreviv** [przemyslawpluta/node-youtube-dl#228]
Version: `2019.02.08`

Action: Download this playlist: `PLZb9bypBWmqEuDLpu2M-L0f93-A8zyOfL`

Command I ran: 
```
youtube-dl --playlist-end 25 --max-filesize 10m --write-info-json -o 'data/youtube/%(resolution)s/%(uploader_id)s/%(id)s.%(ext)s' https://www.youtube.com/playlist\?list\=PLZb9bypBWmqEuDLpu2M-L0f93-A8zyOfL
```

When I run this command manually, I get the message:
```
[download] File is larger than max-filesize (20428898 bytes > 10485760 bytes). Aborting.
```
but when running from python:
```
    subprocess.run("youtube-dl --playlist-end " + str(max_videos) + " --max-filesize 10m --write-info-json -o 'data/youtube/%(resolution)s/%(uploader_id)s/%(id)s.%(ext)s' https://www.youtube.com/playlist\?list\=" + playlist_id, shell=True)
```
Sometimes it ignores the `--max-filesize` parameter and downloads 1.78g of video with id: `bFpmyoC_2pA.f137`

**Comment by Kikobeats** [comment]
This Node.js connector is not doing any extra file size handle, so it delegated directly in the logic present at `youtube-dl` associated with the flag.

Consider open an issue there!
