### ISSUE TITLE
4K download specifications

### ISSUE THREAD

**Issue by JaysQubeXon** [przemyslawpluta/node-youtube-dl#231]
Hi,

First off, thank you for maintaining this repository. I've used it once and it works beautifully.

I am interested in downloading 4K quality videos. I am unsure how to get this done.

If it is possible, could you create an example on an online editor like codesandbox, jsfiddle, or just give me instructions as to how to get this done properly?

So far, I have gotten HD quality videos downloaded by specifying
`['-f', 'bestvideo[ext=mp4]+bestaudio[ext=m4a]']`
in an exec invocation. The result is a separated video and audio files.

Is there a way to ensure a single file?

Thanks again!

**Comment by Kikobeats** [comment]
That's a question more related with youtube-dl that this Node.js connector.

You can use `.getInfo` and pass any flag, so I suppose you need to find the right flags for downloading 4K video as the preferred video resolution.
