### ISSUE TITLE
[Request] Get duration if info doesn't provide it

### ISSUE THREAD

**Issue by kr4ssi** [przemyslawpluta/node-youtube-dl#233]
How about a built-in function to get the duration of the video, if the info doesn't have it?

**Comment by Kikobeats** [comment]
I think it is a bit out of the general purpose scope of the library.

In addition, you can get that using `ffprobe`.

If you can something immediate you can use [Microlink API](https://microlink.io/docs/api/getting-started/overview). 

[See an example getting the duration](https://api.microlink.io/?url=https://twitter.com/futurism/status/882987478541533189&video)
