### ISSUE TITLE
"token" parameter not in video info for unknown reason;

### ISSUE THREAD

**Issue by tuanbs** [przemyslawpluta/node-youtube-dl#236]
Hello there, I got this error this morning, could anyone tell me how I can fix it or workaround it? I see there's a workaround in `youtube-dl` [here](https://github.com/ytdl-org/youtube-dl/issues/20758#issuecomment-486016882). But I don't know how to do it with this package. Thanks in advance.

**Comment by tuanbs** [comment]
Issue is solved by uninstalling and installing it again. This time node-youtube-dl will download the latest version of youtube-dl (2019-04-24) which fixes this issue. Thanks :)).

**Comment by humada05** [comment]
Downloading directly from the github worked, as the npm package is still at 1.13.1
