### ISSUE TITLE
How to import downloader

### ISSUE THREAD

**Issue by serkandaglioglu** [przemyslawpluta/node-youtube-dl#246]
I import youtube-dl "var ytdl = require('@microlink/youtube-dl');" it works.

but this import is not working  "var downloader =require('@microlink/lib/downloader');"
It throws "cannot find module" error

**Comment by yafp** [comment]
@serkandaglioglu 
The project readme shows a simple example regarding using the downloader

```
const downloader = require('youtube-dl/lib/downloader')

downloader('path/to-binary', function error(err, done) {
  'use strict'
  if (err) throw err

  console.log(done)
})
```
