### ISSUE TITLE
Early Stream Termination

### ISSUE THREAD

**Issue by SkyeRangerDelta** [przemyslawpluta/node-youtube-dl#249]
Greetings,

To open, I'd like to apologize if I missed something concerning this topic, I've been looking for an answer for most of the day and I havn't found anything.

**Context** This is running in a Discord.js bot that formerly ran the `ytdl-core` package. That system began having all sorts of error and this one has so far been the most promising system I've used. Unfortunately, while I've managed to get the bot to successfully stream into a Discord channel, it like to terminate early. I cannot find the reason anywhere.

**Code**:
```javascript
//Creates a youtube-dl stream and reads information from it.
        const musicStream = ytdlAlt(song.url, ["--format=bestaudio", "-s", "--skip-download", "--geo-bypass"]);
        musicStream.on('info', i => {
            console.log("[MUSIC STREAM STARTED]");
            console.log("Format: " + i.format + "\nUploader: " + i.uploader + "\nTitle: " + i.title + "\nTrack: " + i.track);
        }).on('end', e => {
            console.log("[MUSIC END]\n");
            console.log(e)
        });
```
^^The stream starts and the information concerning uploader, etc, is all correct.
```javascript
        const playerStream = lcars.serverQueue.connection.playStream(musicStream);
        
        playerStream.on('end', reason => {
            if (reason === 'Stream is not generating quickly enough.') {
                console.log("[MUSI-SYS] PlayStream ended due to excessive lag.");
            } else {
                console.log("PlayStream ended, reason:\n" + reason);
            }

            lcars.serverQueue.songs.shift();
            play(guild, lcars.serverQueue.songs[0], uservc);
        }).on('error', reason => {
            console.log("Readstream error, reason:\n" + reason.stack);
        });
```
^^ Handles the Discord side of things.

When the stream suddenly terminates; I get this output
```
Playstream ended, reason:
undefined
[MUSI-LOG] No song found.
```
--

It never gives me anything concerning it's disconnection. And usually never prints the `[MUSIC END]` tag anywhere. Disconnection typically occurs around 1 minute left in the song before it just disconnects.

I'll try to be as helpful as possible. Perhaps I just need 2 eyes on this, heh. Thanks for any help.

**Comment by Kikobeats** [comment]
hmm this repository doesn't have any relation with `ytdl-core` 🤔

**Comment by SkyeRangerDelta** [comment]
> 
> 
> hmm this repository doesn't have any relation with `ytdl-core` thinking

Correct. It's a dilemma with `youtube-dl`, I merely made a reference for context.

> I've managed to get the bot to successfully stream into a Discord channel, it likes to terminate early. I cannot find the reason anywhere.

I cannot figure out why `youtube-dl` is terminating the stream about ~1m before the end of the video being played.
