### ISSUE TITLE
Getting ERROR: Signature extraction failed: Traceback

### ISSUE THREAD

**Issue by kartik1225** [przemyslawpluta/node-youtube-dl#250]
It was perfectly working fine 5 hours ago from now and now suddenly it stops working and throwing this error.

I am using `2.0.0` version 

For example, it's not working on [this](https://www.youtube.com/watch?v=PT2_F-1esPk) link.

**Comment by gotofritz** [comment]
The following fixed the problem for me

```
cd node_modules/youtube-dl
npm run update
```

**Comment by kartik1225** [comment]
@gotofritz thank you for your suggestion.
but after some time everything is working fine again, I have not changed a single line of code 😅.

but If I get this error again then I will try the solution that you have provided.
