### ISSUE TITLE
Youtube-dl updated its code for Title Extraction.

### ISSUE THREAD

**Issue by adamwoo2444** [przemyslawpluta/node-youtube-dl#254]
Hi youtube changed its code for video extraction and youtube-dl updated its code as well.Please update your code as well, i am unable to extract video title.

**Comment by adamwoo2444** [comment]
@przemyslawpluta

**Comment by Armxy** [comment]
This project currently uses embed youtube-dl executable located in "bin" folder of the project. The quickest workaround is that you install your own copy of youtube-dl, and put the path in "details" config file located in the same folder.

This is what I did on my windows machine with a chocolatey package manager.

`{"version":"2019.08.02","path":"C:\\ProgramData\\chocolatey\\bin\\youtube-dl.exe","exec":"youtube-dl.exe"}`

Hope this helps.

**Comment by Kikobeats** [comment]
Just reinstall it and you are going to fetch the latest youtube-dl binary

**Comment by mayeaux** [comment]
Also, y'all gotta read the docs: https://github.com/przemyslawpluta/node-youtube-dl#update
