### ISSUE TITLE
can not get title by getInfo()

### ISSUE THREAD

**Issue by jwstylet** [przemyslawpluta/node-youtube-dl#255]
-------SOURCE----
var youtubedl = require('youtube-dl');
var url = 'http://www.youtube.com/watch?v=WKsjaOqDXgg';

youtubedl.getInfo(url, ['--format=best'], function(err, info){
    if(err) throw err;
    
    console.log('id:' , info.id);
    console.log('title:' , info.title);
    console.log('url:' , info.url);
    console.log('thumbnail:' , info.thumbnail);
    console.log('description:' , info.description);
    console.log('filename:' , info._filename);
    console.log('format id:' , info.format_id);

})
-------------------------
OUTPUT
-------------------------
id: WKsjaOqDXgg
title: _
url: https://r2---sn-3u-bh2s.googlevideo.com/videoplayback?expire=1565246652&ei=XHBLXea3G6aElQSFk7uwDA&ip=112.169.14.232&id=o-AGaO33VqS11PZEdYi3rDU2OgdYy8U-iQlDTuZ5bPfk-5&itag=43&source=youtube&requiressl=yes&mm=31%2C26&mn=sn-3u-bh2s%2Csn-i3belney&ms=au%2Conr&mv=m&mvi=1&pcm2cms=yes&pl=18&initcwndbps=1443750&mime=video%2Fwebm&gir=yes&clen=20521177&ratebypass=yes&dur=0.000&lmt=1297083858100841&mt=1565224917&fvip=5&c=WEB&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=ALgxI2wwRQIgPpfi5NHjihHCoeSCQQOmwIFqxz3mBQDFsEF_X1EsShYCIQCp48V5judDpbTQJTngbLyzxRqrXSGV-f01S41cgwPY0A%3D%3D&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AHylml4wRQIgd2wg8fRLq9XvWAW2GQRigCTqTxqIwnz7M4SNHN8HrV8CIQCiyNxW9J6p_nIvKQz-ZfAQPCe9vsfEqc64XUa8ftW2Vw%3D%3D
thumbnail: https://i.ytimg.com/vi/WKsjaOqDXgg/hqdefault.jpg
description: An old Red Dwarf eposide where Ace Rimmer saves the Princess Bonjella.
filename: _-WKsjaOqDXgg.webm
format id: 43
-----------------------------
Hello, 
Something wrong with info.title.
It needs updates.
Thanks.

**Comment by JeydinNewWon** [comment]
I'm having the same issue. The title field is simply just an underscore, "_" for whatever video that is searched.

**Comment by JeydinNewWon** [comment]
@jwstylet I've managed to fix the issue by installing v 2.0.1 of this library. That should solve the problem!

**Comment by Kikobeats** [comment]
@JeydinNewWon thanks for the feedback! 🙂
