### ISSUE TITLE
Issues with the downloads

### ISSUE THREAD

**Issue by przemyslawpluta** [przemyslawpluta/node-youtube-dl#26]
It looks like there are issues with the way downloads are being handled since `> v1.3.6`. It works fine as long as all you're downloading is the `video file` only.  

``` js
var video = ytdl('https://www.youtube.com/watch?v=179MiZSibco', ['--max-quality=22']);

var size = 0;
video.on('info', function(info) {
  size = info.size;
  console.log('Got video info');
  console.log('saving to ' + info.filename);
  var output = path.join('/target/to/directory/', info.filename);
  video.pipe(fs.createWriteStream(output));
});
```

The moment you specify additional options like downloading `closed captions` with the video:

``` js
var video = ytdl('https://www.youtube.com/watch?v=179MiZSibco', ['--max-quality=22', '--write-srt', '--srt-lang=en']);
```

Only the video is being downloaded into the specified location while the `closed caption` file is being downloaded in to the local directory.

This works as expected when the arguments are passed to the `./bin/youtube-dl` directly.

**Comment by hugolpz** [comment]
This don't work for me. Did this code got broken ?

    var video = ytdl('https://www.youtube.com/watch?v=179MiZSibco', ['--max-quality=22', '--write-srt', '--srt-lang=en']);
