### ISSUE TITLE
Can't continue download where I left off.

### ISSUE THREAD

**Issue by GoogleSites** [przemyslawpluta/node-youtube-dl#266]
Node: 13.0.1
node-youtube-dl: 2.1.0

Issue: When I follow [the official tutorial](https://www.npmjs.com/package/youtube-dl#resuming-partially-downloaded-videos) for resuming a download, I set it to start the video at 1000000 bytes, but it downloads the entire video anyways.

Expected: It cuts off the first part of the video as I set it to start at a certain point.

Code:
```js
const youtubedl = require('youtube-dl')
const fs = require('fs')
const output = 'myvideo.mp4'

const downloaded = 1000000;

const video = youtubedl('https://www.youtube.com/watch?v=179MiZSibco',

  // Optional arguments passed to youtube-dl.
  ['--format=18'],

  // start will be sent as a range header
  { start: downloaded, cwd: __dirname })

// Will be called when the download starts.
video.on('info', function(info) {
  console.log('Download started')
  console.log('filename: ' + info._filename)

  // info.size will be the amount to download, add
  let total = info.size + downloaded
  console.log('size: ' + total)

  if (downloaded > 0) {
    // size will be the amount already downloaded
    console.log('resuming from: ' + downloaded)

    // display the remaining bytes to download
    console.log('remaining bytes: ' + info.size)
  }
})

video.pipe(fs.createWriteStream(output, { flags: 'a' }))

// Will be called if download was already completed and there is nothing more to download.
video.on('complete', function complete(info) {
  'use strict'
  console.log('filename: ' + info._filename + ' already downloaded.')
})

video.on('end', function() {
  console.log('finished downloading!')
})
```

**Comment by dhiahassen** [comment]
same issue here

**Comment by mzalazar** [comment]
This is weird, I tested that code and it's working for me, i have node v11.15.0 and when i hit CTRL + C (while downloading)... a file is left in that directory, it's called: '1 1 1-179MiZSibco.mp4.part', I changed the number of downloaded bytes of course and launched this same script... and this is the result:

Download started
filename: 1 1 1-179MiZSibco.mp4
size: 8336433
resuming from: 3226355
remaining bytes: 5110078
finished downloading!

**Comment by yafp** [comment]
i just tested resume with the following condition

*  using `youtube.exec` 
* using node-youtube-dl featuring youtube-dl binary 2020.01.24
* using `--continue`

In this particular setup -> resume works out of the box.

**Comment by Harkunwar** [comment]
+1
