### ISSUE TITLE
Could you add an example for extracting audio from a video url to the readme.

### ISSUE THREAD

**Issue by yafp** [przemyslawpluta/node-youtube-dl#273]
Hey,

i searched for a while, found several issues regarding audio extracting, but am still unable to have my code working.

Assuming it is supported: could you please add an example for extracting audio from a video url?

refs: #110 #208 #158

**Comment by yafp** [comment]
i solved it by using 

```
youtubeDlParameter = ['-f', 'bestaudio', '--extract-audio', '--audio-format', 'mp3', '--audio-quality', '0', '-o', targetPath, '--prefer-ffmpeg', '--ffmpeg-location', ffmpeg.path]

const video = youtubedl.exec(url, youtubeDlParameter, {}, function (err, output) {
...
```

But i guess adding an audio-specific example to the readme would still solve beginner issues for some of us ;)

**Comment by Kikobeats** [comment]
Can you make a PR for adding it to README? 🙂

**Comment by yafp** [comment]
Well i could provide my example using youtubedl.exec - but i am still wondering if extracting audio is ONLY possible by using .exec
