### ISSUE TITLE
Doesn't work with Electron because of Asar unpacking

### ISSUE THREAD

**Issue by EthanSK** [przemyslawpluta/node-youtube-dl#276]
Since you change the execution from execFile to universal, the binary is not properly detected in an electron build. Please provide us some options for getting the path, such as the ability to replace the app.asar in the path to app.unpacked.asar like such:

``` path_to_bin.replace("app.asar", "app.asar.unpacked")```

**Comment by Kikobeats** [comment]
You can set the path using https://github.com/przemyslawpluta/node-youtube-dl#changing-the-binary-path

**Comment by AlexSHoffman** [comment]
@EthanSK have you found a solution for this? @Kikobeats solution doesn't work. It throws an error on ` require('youtube-dl')` so it doesn't let you set anything

**Comment by EthanSK** [comment]
His solution did work. Just do

`const youtubedl = require("youtube-dl")
youtubedl.setYtdlBinary(
  youtubedl.getYtdlBinary().replace("app.asar", "app.asar.unpacked")
)`

**Comment by AlexSHoffman** [comment]
@EthanSK thanks for the code example

For some reason it doesn't work for me either. Webpack keeps throwing this error:

```
Invalid package [project_path]\node_modules\electron\dist\resources\electron.asar
```

I tired both your code and the following:
```
const youtubedl = require("youtube-dl")
youtubedl.setYtdlBinary('C:/test/youtube-dl')
```
