### ISSUE TITLE
crop and download?

### ISSUE THREAD

**Issue by lacivert** [przemyslawpluta/node-youtube-dl#280]
Is there a way to download a video only a specific time instead of download all? If yes, it would be better to write this way on the documents.

**Comment by yafp** [comment]
@lacivert 
Just to be sure i understood the question.

You are asking if it is possible to download only the first 2 minutes of a 5 minute video?

**Comment by Kikobeats** [comment]
@yafp Yes, I think.

If it's a thing supported at youtube-dl, then it can be done using flags (and a PR adding an example into README is very welcome!)

Otherwise, it's a thing out of the scope of the library.

**Comment by lacivert** [comment]
@yafp correct, for example I need two mins (lets say between 12:00-14:00) of 1 hour long video. I have to download all which would take long time. Instead, just download the specific time would be better

**Comment by lacivert** [comment]
@Kikobeats Thank you, I guess that is a feature request waiting for a long time in youtube-dl

https://github.com/ytdl-org/youtube-dl/issues/622

**Comment by Kikobeats** [comment]
that's great, I hope to see it soon 🙂
