### ISSUE TITLE
Error while running .getExtractors

### ISSUE THREAD

**Issue by yafp** [przemyslawpluta/node-youtube-dl#286]
I am using the following code to get the list of supported extractors

```
const youtubedl = require('youtube-dl')
youtubedl.getExtractors(true, function (error, list) {
        if (error) {
            throw error
        }

        // show all extractors in console
        for (let i = 0; i < list.length; i++) {
            // ....
        }
    })
```

The application itself is logging errors using the sentry framework.It seems like some hosts throw errors while running the above code. 

Example from my sentry logs:

```
Error makeError(execa/lib/error)

Error

Command failed with exit code 3221225781: x:\USER\APPLICATIONPATH\\node_modules\youtube-dl\bin\youtube-dl.exe --extractor-descriptions --encoding utf8


app:///node_modules/execa/lib/error.js in makeError at line 56:11
app:///node_modules/execa/index.js in handlePromise at line 114:26
```

**Sidenode:**
Somehow i got the impression - based on the logs that this happens most on Windows 10 machines.

Any idea why this might happen?

**Comment by yafp** [comment]
This is most likely caused by myself.

I am creating the linux and windows builds from within linux.
As a result the node_modules folder of youtube-dl contains only an executable for linux (youtube-dl not youtube-dl.exe)

This might cause issues. The windows builds do detect the binary itself using getYtdlBinary() - but i assume executing (.exec) the linux binary on windows is then causing the error.

Conclusion for me: build windows on windows ;)

**Comment by Kikobeats** [comment]
@yafp Thanks for update the issue, I added `question` tag to make easy found it and help people with similar problems 🙂

**Comment by yafp** [comment]
np
