### ISSUE TITLE
Can best video quality 1920x1080 (mp4) and best audio quality (m4a) be merged into a single mp4?

### ISSUE THREAD

**Issue by inglesuniversal** [przemyslawpluta/node-youtube-dl#307]
Tried this argument but it did not work

`['-f', '137+141'],`

Any pointers?

Best regards and stay safe!

**Comment by jcsteck** [comment]
I'm running into the exact same issue! Please let me know if you found a solution.

**Comment by inglesuniversal** [comment]
not yet.. Hope the author can take a look at this issue.

Stay SAFE

**Comment by Tzahi12345** [comment]
Probably related to [this](https://github.com/przemyslawpluta/node-youtube-dl/issues/221)

**Comment by jcsteck** [comment]
Sounds about right! I ended up using the binary. Thank you guys!

**Comment by brow1726** [comment]
Yes it can. You need to run it in the exec(). 
`return new Promise((res, rej) => {
        youtubedl.exec(url, ['-f', `${formats.video.format}+${formats.audio.format}`, '--merge-output-format', 'mp4', '-o', `${outputPath}`],{maxBuffer: Infinity }, (err, output) => {
            if (err) {
                console.log('******************** err ********************');
                console.log(err);
                console.log('************************************************');
                rej(err)
            }
            console.log('******************** output ********************');
            console.log(output);
            console.log('************************************************');
            res(output);
        });
    })`
