### ISSUE TITLE
NPM Install Fails with Invalid Cert Error

### ISSUE THREAD

**Issue by edgework** [przemyslawpluta/node-youtube-dl#310]
```
npm install

> youtube-dl@3.0.2 postinstall /opt/server/node_modules/youtube-dl
> node ./scripts/download.js

Error: certificate has expired
    at TLSSocket.<anonymous> (_tls_wrap.js:1116:38)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket._finishInit (_tls_wrap.js:643:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:473:38)
```

but https://yt-dl.org/downloads/latest/youtube-dl  has a valid cert and downloads fine on web browsers.

**Comment by jaruba** [comment]
This is happening for me too on Win and OSX, but Linux seems to work for some reason.

**Comment by bradleyjucsc** [comment]
Looks like a result of the download URL: ```echo | openssl s_client -showcerts -servername yt-dl.org -connect yt-dl.org:443```

**Comment by IAmIndra** [comment]
Same problem here on Windows 10. Still appears to run fine on my macbook Pro

**Comment by edgework** [comment]
This issue has nothing to do with this NPM Package.   See

https://support.sectigo.com/Com_KnowledgeDetailPage?Id=kA03l00000117LT

**Comment by bradleyjucsc** [comment]
Thank you @edgework, appreciate the pointers.

**Comment by mayeaux** [comment]
> https://support.sectigo.com/Com_KnowledgeDetailPage?Id=kA03l00000117LT

What's the fix? Why is this STILL erroring out? :|

**Comment by mayeaux** [comment]
> This issue has nothing to do with this NPM Package. Its, indirectly an issue with the certificate on the yt-dl.org. See https://support.sectigo.com/Com_KnowledgeDetailPage?Id=kA03l00000117LT
> 
> To solve it, remove mozilla/AddTrust_External_Root.crt from your local ca-cert store.
> 
> For Debian
> 
> * edit /etc/ca-certificates.conf and put a bang/exclamation mark (!) before mozilla/AddTrust_External_Root.crt
> * Run update-ca-certificates
> 
> For other's Google `remove ca-certificates <your os>`

What's the fix? Why is this STILL erroring out? :|

**Comment by edgework** [comment]
upgrade Node to at least 12.x
