### ISSUE TITLE
Error in installing package

### ISSUE THREAD

**Issue by dasaseshadri** [przemyslawpluta/node-youtube-dl#314]
I am using : sudo npm install -g udacimak, and below error is being thrown:

> youtube-dl@3.0.2 postinstall /usr/local/lib/node_modules/udacimak/node_modules/youtube-dl
> node ./scripts/download.js

sh: 1: node: not found
/usr/local/lib
`-- (empty)

npm ERR! Linux 4.4.0-21-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "udacimak"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! youtube-dl@3.0.2 postinstall: `node ./scripts/download.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the youtube-dl@3.0.2 postinstall script 'node ./scripts/download.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the youtube-dl package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./scripts/download.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs youtube-dl
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls youtube-dl
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/lib/npm-debug.log
npm ERR! code 1

Please provide quick solution.

**Comment by Naia-love** [comment]
Like wrote on the error, you use a totally out of date version of Node, idk which version is required at least by these modules, but please use at least node 12.
and also the first line says "node not found" so check if you installed it well _or it's just not installed the same way as new versions_
but so it's almost sure it's not a problem from the module
