### ISSUE TITLE
New maintainers?

### ISSUE THREAD

**Issue by brunobg** [przemyslawpluta/node-youtube-dl#318]
This project doesn't seem to be actively maintained anymore. Are you looking for maintainers? I'm using this package so this interests me, and I could clean up the existing issues and the PRs.

**Comment by brunobg** [comment]
@Kikobeats?

**Comment by Kikobeats** [comment]
I'm not actively maintaining the project because I'm not actively using it; just it's working fine for the use case I'm using it

If you contribute using PR you will be eventually a maintainer; I'll happy to merge any PR with green tests 🙂

**Comment by brunobg** [comment]
Ok. I'll take a look at what's going on and see what I can fix on a fork and send PRs. Is there anything missing on https://github.com/przemyslawpluta/node-youtube-dl/pull/298 to accept it? You can close the issue too, thanks.

**Comment by Kikobeats** [comment]
The PR says "The code is untested, i just replaced the parts.", need a test for that

**Comment by brunobg** [comment]
Pushed a fix for that was properly tested. The very download of travis already tests that code, too. 

I'll send other PRs. There are issues that could be closed immediately too without code. I'll be actively using this project. Can I ping you for new releases until you add me as maintainer? Thanks.
