### ISSUE TITLE
How to execute just '--get-url'? 

### ISSUE THREAD

**Issue by Aparus** [przemyslawpluta/node-youtube-dl#324]
Hi! Thank you for great driver! 

When I run in terminal `youtube-dl --get-url https://youtu.be/mH4hAMqAnWw`, 
I get just 2 direct links:
- on mp4 file without sound
- on webm file audio only. 
![Screenshot from 2020-08-23 10-51-17](https://user-images.githubusercontent.com/1222611/90974396-79eeb000-e533-11ea-8998-14bbdccd01dd.png)

I can't reproduce this with this package. 
For now I have done: 
```
app.get("/direct-url/:videoId", function (req, res) {
  const { videoId } = req.params;
  const url = `https://www.youtube.com/watch?v=${videoId}`;
  const options = ["--get-url"];
  youtubedl.getInfo(url, options, function (err, info) {
    if (err) throw err;
    const response = htmlPage(info);
    res.send(response);
  });
});
```
But it returns lots of data, I don't need them... 
I tried also just to run youtubedl , not "getInfo", and had not get that 2 direct links...

**Comment by PrasadBroo** [comment]
```
app.get('/get_formats',(req,res)=>{
  const url = 'http://www.youtube.com/watch?v=e_S9VvJM1PI'
  // Optional arguments passed to youtube-dl.
  const options = ['--username=user', '--password=hunter2']
  youtubedl.getInfo(url, options, function(err, info) {
  if (err) throw err
  res.json(info.formats)
})
})
```
this way you will get formats only as info is object itself. you can get  what ever you want  whithin that object like headers  sent etc.

**Comment by Aparus** [comment]
> ```
> app.get('/get_formats',(req,res)=>{
>   const url = 'http://www.youtube.com/watch?v=e_S9VvJM1PI'
>   // Optional arguments passed to youtube-dl.
>   const options = ['--username=user', '--password=hunter2']
>   youtubedl.getInfo(url, options, function(err, info) {
>   if (err) throw err
>   res.json(info.formats)
> })
> })
> ```
> 
> this way you will get formats only as info is object itself. you can get what ever you want whithin that object like headers sent etc.

there is more than two links. there is dozens. How I know that 2 links ? ))
