### ISSUE TITLE
[question] res.send(audio) : download audio with stream

### ISSUE THREAD

**Issue by mirsella** [przemyslawpluta/node-youtube-dl#331]
hello, I have an express app and I planned on sending the mp3 file with `video.pipe(res)` but I can't download the file as an mp3, options as follow `['--audio-format', 'mp3']` and i tried with adding a '-x' too. it send the youtube video as a mp4 file, and with the video.

and another issue, which is probably not with youtube-dl, the file being downloaded just have the name of the nodejs endpoint, like if it's at like /mp3, the file downloaded is just named "mp3" without even the file extension, if someone knows how to change the name of file even if it's not because of youtube-dl

**Comment by deniscerri** [comment]
My issue is that im telling it do download audio only and it is still downloading a video. its weird. i write the content disposition as mp3. the file shows as mp3 when i download it. when i open on vlc, it shows video???? im confused
