### ISSUE TITLE
Is... Is this... Is this legal?

### ISSUE THREAD

**Issue by thecoder08** [przemyslawpluta/node-youtube-dl#342]
Is it legal to download videos from youtube without their or the creator's consent? I know creators can download their own videos, but if you download videos without advertisements, then youtube and the content create are losing money!

**Comment by Tzahi12345** [comment]
youtube-dl is 100% legal, just like qBittorrent is legal. They are tools, it is up to the individual user to use it legally.

node-youtube-dl is even further removed from this legality question, in that they are just a wrapper for a tool which is perfectly legal in and of itself.

Is it legal to download a video from YT without the creator's consent? No. Is it legal to stab someone with a pair of scissors? You are essentially asking if the scissor manufacturer is legally liable in that situation, the answer is quite clear.

**Comment by thecoder08** [comment]
So considering your scissor analogy, does this mean you're suggesting that user only download their own videos? in that case, they could just do it from the youtube website. Scissors have a purpose beyond stabbing people, youtube-dl does not have a purpose beyond stealing videos.

**Comment by Tzahi12345** [comment]
>youtube-dl does not have a purpose beyond stealing videos

Sorry this is just wrong. Many people use it to archive their own videos, in fact it is simply a generic video downloading tool not tied to a single website. Is the download button on the default chrome video player just there to "steal videos"? It's literally the same thing.

**Comment by wkronmiller** [comment]
@thecoder08 This project is just a wrapper around youtube-dl, whose legality has already been heavily discussed elsewhere. 

As an example you can read the Electronic Frontiers Foundation's letter to GitHub in defense of youtube-dl: https://www.eff.org/files/2020/11/17/eff_letter_to_github_re_youtube-dl_11152020.pdf

You are entitled to your opinions, but a substantial and significant population of developers feels differently from you. I would ask you to try to be a good citizen of the open source community, and not antagonize busy maintainers with confrontational GitHub issues. 

The maintainers of this project have worked hard to provide a free and open-source product that people such as myself find valuable. If you don't like it, then don't use it. 

Thank you.

**Comment by cinixyz** [comment]
> 
> 
> in that case, they could just do it from the youtube website.

IIRC, youtube's video download feature is limited to 720p h264 files. Although that might be sufficient for archival purposes, it's still a huge loss of quality, especially if the source file is in 4K.
