### ISSUE TITLE
Cannot read property 'statusCode' of undefined

### ISSUE THREAD

**Issue by shouvik44** [przemyslawpluta/node-youtube-dl#353]
Trying to build, and getting this error:
   /tmp/build_7bb175f2/node_modules/youtube-dl/lib/downloader.js:20
remote:                if (res.statusCode !== 302) {
remote:                        ^
remote:        
remote:        TypeError: Cannot read property 'statusCode' of undefined
remote:            at Request._callback (/tmp/build_7bb175f2/node_modules/youtube-dl/lib/downloader.js:20:17)
remote:            at self.callback (/tmp/build_7bb175f2/node_modules/request/request.js:185:22)
remote:            at Request.emit (events.js:311:20)
remote:            at Request.onRequestError (/tmp/build_7bb175f2/node_modules/request/request.js:881:8)
remote:            at ClientRequest.emit (events.js:311:20)
remote:            at TLSSocket.socketErrorListener (_http_client.js:426:9)
remote:            at TLSSocket.emit (events.js:311:20)
remote:            at emitErrorNT (internal/streams/destroy.js:92:8)
remote:            at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
remote:            at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by Kikobeats** [comment]
Can you try the latest version? this should be fixed 🙂

**Comment by shouvik44** [comment]
It works - thank you!
