### ISSUE TITLE
Doesnt download from rutube.ru

### ISSUE THREAD

**Issue by IvanRave** [przemyslawpluta/node-youtube-dl#49]
Error: undefined is not a valid uri or options object.
- at request (/home/ivanrave/gvmg/vmg-ytb/node_modules/youtube-dl/node_modules/request/index.js:42:41)
- at /home/ivanrave/gvmg/vmg-ytb/node_modules/youtube-dl/lib/youtube-dl.js:49:15

for example: http://rutube.ru/video/c441461d05cf8cdc2682d2462b4806ea/

**Comment by dporechny** [comment]
Still problems with Rutube. It saves file, but it almost empty, ~1 kb.
